-- Table --
CREATE TABLE `languages` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` char(80) CHARACTER SET utf8 DEFAULT NULL,
  `iso_639-1` char(3) CHARACTER SET utf8 DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=136 ;

-- Languages --
INSERT INTO `languages` VALUES(1, 'Abkhazian', 'ab');
INSERT INTO `languages` VALUES(2, 'Afar', 'aa');
INSERT INTO `languages` VALUES(3, 'Afrikaans', 'af');
INSERT INTO `languages` VALUES(4, 'Akan', 'ak');
INSERT INTO `languages` VALUES(5, 'Albanian', 'sq');
INSERT INTO `languages` VALUES(6, 'Amharic', 'am');
INSERT INTO `languages` VALUES(7, 'Arabic', 'ar');
INSERT INTO `languages` VALUES(8, 'Aragonese', 'an');
INSERT INTO `languages` VALUES(9, 'Armenian', 'hy');
INSERT INTO `languages` VALUES(10, 'Assamese', 'as');
INSERT INTO `languages` VALUES(11, 'Avaric', 'av');
INSERT INTO `languages` VALUES(12, 'Avestan', 'ae');
INSERT INTO `languages` VALUES(13, 'Aymara', 'ay');
INSERT INTO `languages` VALUES(14, 'Azerbaijani', 'az');
INSERT INTO `languages` VALUES(15, 'Bambara', 'bm');
INSERT INTO `languages` VALUES(16, 'Bashkir', 'ba');
INSERT INTO `languages` VALUES(17, 'Basque', 'eu');
INSERT INTO `languages` VALUES(18, 'Belarusian', 'be');
INSERT INTO `languages` VALUES(19, 'Bengali', 'bn');
INSERT INTO `languages` VALUES(20, 'Bihari languages', 'bh');
INSERT INTO `languages` VALUES(21, 'Bislama', 'bi');
INSERT INTO `languages` VALUES(22, 'Bosnian', 'bs');
INSERT INTO `languages` VALUES(23, 'Breton', 'br');
INSERT INTO `languages` VALUES(24, 'Bulgarian', 'bg');
INSERT INTO `languages` VALUES(25, 'Burmese', 'my');
INSERT INTO `languages` VALUES(26, 'Catalan, Valencian', 'ca');
INSERT INTO `languages` VALUES(27, 'Chamorro', 'ch');
INSERT INTO `languages` VALUES(28, 'Chechen', 'ce');
INSERT INTO `languages` VALUES(29, 'Chichewa, Chewa, Nyanja', 'ny');
INSERT INTO `languages` VALUES(30, 'Chinese', 'zh');
INSERT INTO `languages` VALUES(31, 'Chuvash', 'cv');
INSERT INTO `languages` VALUES(32, 'Cornish', 'kw');
INSERT INTO `languages` VALUES(33, 'Corsican', 'co');
INSERT INTO `languages` VALUES(34, 'Cree', 'cr');
INSERT INTO `languages` VALUES(35, 'Croatian', 'hr');
INSERT INTO `languages` VALUES(36, 'Czech', 'cs');
INSERT INTO `languages` VALUES(37, 'Danish', 'da');
INSERT INTO `languages` VALUES(38, 'Divehi, Dhivehi, Maldivian', 'dv');
INSERT INTO `languages` VALUES(39, 'Dutch, Flemish', 'nl');
INSERT INTO `languages` VALUES(40, 'Dzongkha', 'dz');
INSERT INTO `languages` VALUES(41, 'English', 'en');
INSERT INTO `languages` VALUES(42, 'Esperanto', 'eo');
INSERT INTO `languages` VALUES(43, 'Estonian', 'et');
INSERT INTO `languages` VALUES(44, 'Ewe', 'ee');
INSERT INTO `languages` VALUES(45, 'Faroese', 'fo');
INSERT INTO `languages` VALUES(46, 'Fijian', 'fj');
INSERT INTO `languages` VALUES(47, 'Finnish', 'fi');
INSERT INTO `languages` VALUES(48, 'French', 'fr');
INSERT INTO `languages` VALUES(49, 'Fulah', 'ff');
INSERT INTO `languages` VALUES(50, 'Galician', 'gl');
INSERT INTO `languages` VALUES(51, 'Georgian', 'ka');
INSERT INTO `languages` VALUES(52, 'German', 'de');
INSERT INTO `languages` VALUES(53, 'Greek (modern)', 'el');
INSERT INTO `languages` VALUES(54, 'Guaraní', 'gn');
INSERT INTO `languages` VALUES(55, 'Gujarati', 'gu');
INSERT INTO `languages` VALUES(56, 'Haitian, Haitian Creole', 'ht');
INSERT INTO `languages` VALUES(57, 'Hausa', 'ha');
INSERT INTO `languages` VALUES(58, 'Hebrew (modern)', 'he');
INSERT INTO `languages` VALUES(59, 'Herero', 'hz');
INSERT INTO `languages` VALUES(60, 'Hindi', 'hi');
INSERT INTO `languages` VALUES(61, 'Hiri Motu', 'ho');
INSERT INTO `languages` VALUES(62, 'Hungarian', 'hu');
INSERT INTO `languages` VALUES(63, 'Interlingua', 'ia');
INSERT INTO `languages` VALUES(64, 'Indonesian', 'id');
INSERT INTO `languages` VALUES(65, 'Interlingue', 'ie');
INSERT INTO `languages` VALUES(66, 'Irish', 'ga');
INSERT INTO `languages` VALUES(67, 'Igbo', 'ig');
INSERT INTO `languages` VALUES(68, 'Inupiaq', 'ik');
INSERT INTO `languages` VALUES(69, 'Ido', 'io');
INSERT INTO `languages` VALUES(70, 'Icelandic', 'is');
INSERT INTO `languages` VALUES(71, 'Italian', 'it');
INSERT INTO `languages` VALUES(72, 'Inuktitut', 'iu');
INSERT INTO `languages` VALUES(73, 'Japanese', 'ja');
INSERT INTO `languages` VALUES(74, 'Javanese', 'jv');
INSERT INTO `languages` VALUES(75, 'Kalaallisut, Greenlandic', 'kl');
INSERT INTO `languages` VALUES(76, 'Kannada', 'kn');
INSERT INTO `languages` VALUES(77, 'Kanuri', 'kr');
INSERT INTO `languages` VALUES(78, 'Kashmiri', 'ks');
INSERT INTO `languages` VALUES(79, 'Kazakh', 'kk');
INSERT INTO `languages` VALUES(80, 'Central Khmer', 'km');
INSERT INTO `languages` VALUES(81, 'Kikuyu, Gikuyu', 'ki');
INSERT INTO `languages` VALUES(82, 'Kinyarwanda', 'rw');
INSERT INTO `languages` VALUES(83, 'Kirghiz, Kyrgyz', 'ky');
INSERT INTO `languages` VALUES(84, 'Komi', 'kv');
INSERT INTO `languages` VALUES(85, 'Kongo', 'kg');
INSERT INTO `languages` VALUES(86, 'Korean', 'ko');
INSERT INTO `languages` VALUES(87, 'Kurdish', 'ku');
INSERT INTO `languages` VALUES(88, 'Kuanyama, Kwanyama', 'kj');
INSERT INTO `languages` VALUES(89, 'Latin', 'la');
INSERT INTO `languages` VALUES(90, 'Luxembourgish, Letzeburgesch', 'lb');
INSERT INTO `languages` VALUES(91, 'Ganda', 'lg');
INSERT INTO `languages` VALUES(92, 'Limburgan, Limburger, Limburgish', 'li');
INSERT INTO `languages` VALUES(93, 'Lingala', 'ln');
INSERT INTO `languages` VALUES(94, 'Lao', 'lo');
INSERT INTO `languages` VALUES(95, 'Lithuanian', 'lt');
INSERT INTO `languages` VALUES(96, 'Luba-Katanga', 'lu');
INSERT INTO `languages` VALUES(97, 'Latvian', 'lv');
INSERT INTO `languages` VALUES(98, 'Manx', 'gv');
INSERT INTO `languages` VALUES(99, 'Macedonian', 'mk');
INSERT INTO `languages` VALUES(100, 'Malagasy', 'mg');
INSERT INTO `languages` VALUES(101, 'Malay', 'ms');
INSERT INTO `languages` VALUES(102, 'Malayalam', 'ml');
INSERT INTO `languages` VALUES(103, 'Maltese', 'mt');
INSERT INTO `languages` VALUES(104, 'Maori', 'mi');
INSERT INTO `languages` VALUES(105, 'Marathi', 'mr');
INSERT INTO `languages` VALUES(106, 'Marshallese', 'mh');
INSERT INTO `languages` VALUES(107, 'Mongolian', 'mn');
INSERT INTO `languages` VALUES(108, 'Nauru', 'na');
INSERT INTO `languages` VALUES(109, 'Navajo, Navaho', 'nv');
INSERT INTO `languages` VALUES(110, 'North Ndebele', 'nd');
INSERT INTO `languages` VALUES(111, 'Nepali', 'ne');
INSERT INTO `languages` VALUES(112, 'Ndonga', 'ng');
INSERT INTO `languages` VALUES(113, 'Norwegian Bokmål', 'nb');
INSERT INTO `languages` VALUES(114, 'Norwegian Nynorsk', 'nn');
INSERT INTO `languages` VALUES(115, 'Norwegian', 'no');
INSERT INTO `languages` VALUES(116, 'Sichuan Yi, Nuosu', 'ii');
INSERT INTO `languages` VALUES(117, 'South Ndebele', 'nr');
INSERT INTO `languages` VALUES(118, 'Occitan', 'oc');
INSERT INTO `languages` VALUES(119, 'Ojibwa', 'oj');
INSERT INTO `languages` VALUES(120, 'Church Slavic, Church Slavonic, Old Church Slavonic, Old Slavonic, Old Bulgarian', 'cu');
INSERT INTO `languages` VALUES(121, 'Oromo', 'om');
INSERT INTO `languages` VALUES(122, 'Oriya', 'or');
INSERT INTO `languages` VALUES(123, 'Ossetian, Ossetic', 'os');
INSERT INTO `languages` VALUES(124, 'Panjabi, Punjabi', 'pa');
INSERT INTO `languages` VALUES(125, 'Pali', 'pi');
INSERT INTO `languages` VALUES(126, 'Persian', 'fa');
INSERT INTO `languages` VALUES(127, 'Polabian', 'pox');
INSERT INTO `languages` VALUES(128, 'Polish', 'pl');
INSERT INTO `languages` VALUES(129, 'Pashto, Pushto', 'ps');
INSERT INTO `languages` VALUES(130, 'Portuguese', 'pt');
INSERT INTO `languages` VALUES(131, 'Quechua', 'qu');
INSERT INTO `languages` VALUES(132, 'Romansh', 'rm');
INSERT INTO `languages` VALUES(133, 'Rundi', 'rn');
INSERT INTO `languages` VALUES(134, 'Romanian, Moldavian, Moldovan', 'ro');
INSERT INTO `languages` VALUES(135, 'Russian', 'ru');
INSERT INTO `languages` VALUES(136, 'Sanskrit', 'sa');
INSERT INTO `languages` VALUES(137, 'Sardinian', 'sc');
INSERT INTO `languages` VALUES(138, 'Sindhi', 'sd');
INSERT INTO `languages` VALUES(139, 'Northern Sami', 'se');
INSERT INTO `languages` VALUES(140, 'Samoan', 'sm');
INSERT INTO `languages` VALUES(141, 'Sango', 'sg');
INSERT INTO `languages` VALUES(142, 'Serbian', 'sr');
INSERT INTO `languages` VALUES(143, 'Gaelic, Scottish Gaelic', 'gd');
INSERT INTO `languages` VALUES(144, 'Shona', 'sn');
INSERT INTO `languages` VALUES(145, 'Sinhala, Sinhalese', 'si');
INSERT INTO `languages` VALUES(146, 'Slovak', 'sk');
INSERT INTO `languages` VALUES(147, 'Slovenian', 'sl');
INSERT INTO `languages` VALUES(148, 'Somali', 'so');
INSERT INTO `languages` VALUES(149, 'Southern Sotho', 'st');
INSERT INTO `languages` VALUES(150, 'Spanish, Castilian', 'es');
INSERT INTO `languages` VALUES(151, 'Sundanese', 'su');
INSERT INTO `languages` VALUES(152, 'Swahili', 'sw');
INSERT INTO `languages` VALUES(153, 'Swati', 'ss');
INSERT INTO `languages` VALUES(154, 'Swedish', 'sv');
INSERT INTO `languages` VALUES(155, 'Tamil', 'ta');
INSERT INTO `languages` VALUES(156, 'Telugu', 'te');
INSERT INTO `languages` VALUES(157, 'Tajik', 'tg');
INSERT INTO `languages` VALUES(158, 'Thai', 'th');
INSERT INTO `languages` VALUES(159, 'Tigrinya', 'ti');
INSERT INTO `languages` VALUES(160, 'Tibetan', 'bo');
INSERT INTO `languages` VALUES(161, 'Turkmen', 'tk');
INSERT INTO `languages` VALUES(162, 'Tagalog', 'tl');
INSERT INTO `languages` VALUES(163, 'Tswana', 'tn');
INSERT INTO `languages` VALUES(164, 'Tonga (Tonga Islands)', 'to');
INSERT INTO `languages` VALUES(165, 'Turkish', 'tr');
INSERT INTO `languages` VALUES(166, 'Tsonga', 'ts');
INSERT INTO `languages` VALUES(167, 'Tatar', 'tt');
INSERT INTO `languages` VALUES(168, 'Twi', 'tw');
INSERT INTO `languages` VALUES(169, 'Tahitian', 'ty');
INSERT INTO `languages` VALUES(170, 'Uighur, Uyghur', 'ug');
INSERT INTO `languages` VALUES(171, 'Ukrainian', 'uk');
INSERT INTO `languages` VALUES(172, 'Urdu', 'ur');
INSERT INTO `languages` VALUES(173, 'Uzbek', 'uz');
INSERT INTO `languages` VALUES(174, 'Venda', 've');
INSERT INTO `languages` VALUES(175, 'Vietnamese', 'vi');
INSERT INTO `languages` VALUES(176, 'Volapük', 'vo');
INSERT INTO `languages` VALUES(177, 'Walloon', 'wa');
INSERT INTO `languages` VALUES(178, 'Welsh', 'cy');
INSERT INTO `languages` VALUES(179, 'Wolof', 'wo');
INSERT INTO `languages` VALUES(180, 'Western Frisian', 'fy');
INSERT INTO `languages` VALUES(181, 'Xhosa', 'xh');
INSERT INTO `languages` VALUES(182, 'Yiddish', 'yi');
INSERT INTO `languages` VALUES(183, 'Yoruba', 'yo');
INSERT INTO `languages` VALUES(184, 'Zhuang, Chuang', 'za');
INSERT INTO `languages` VALUES(185, 'Zulu', 'zu');
